B3_URL = 'http://www.b3.com.br/pt_br/produtos-e-servicos/negociacao/renda-variavel/empresas-listadas.htm'
CHROME_DRIVER = 'chromedriver'
FIREFOX_DRIVER = 'geckodriver'
B3_FRAME = 'bvmf_iframe'
STARTING_CLASS_NAME = 'letra'
B3_COMPANY_FRAME = 'ctl00_contentPlaceHolderConteudo_iframeCarregadorPaginaExterna'
COMPANY_CLASS = 'LinkCodNeg'
